# Generated by Django 5.1.4 on 2024-12-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
