# Generated by Django 5.1.4 on 2024-12-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureFileShareApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('extension', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('file_url', models.CharField(max_length=500)),
                ('file_size', models.CharField(max_length=300)),
                ('updated_at', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('updated_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('role_permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permissions', models.CharField(max_length=200)),
                ('role_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SharedFileUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('can_view', models.BooleanField()),
                ('can_download', models.BooleanField()),
                ('share_file_id', models.IntegerField()),
                ('share_to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShareFile',
            fields=[
                ('share_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.IntegerField()),
                ('shared_by', models.IntegerField()),
                ('shared_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='role_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
