# Generated by Django 5.1.4 on 2024-12-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureFileShareApp', '0002_filemetadata_rolepermission_sharedfileusers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetadata',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
