# Generated by Django 5.1.4 on 2024-12-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureFileShareApp', '0003_alter_filemetadata_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='file_size',
            field=models.CharField(max_length=500),
        ),
    ]
